spring.application.name=cybershield

# 1. C?u hình PostgreSQL (Ch?y code Local ch?c vào Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/cybershield
spring.datasource.username=admin
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. C?u hình JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
# B? spring.jpa.properties.hibernate.dialect ?? tránh rác log (Spring t? nh?n di?n)

# 3. C?u hình Redis (Ch?y code Local ch?c vào Docker)
spring.data.redis.host=localhost
spring.data.redis.port=6379

# 4. C?u hình JWT
# Key này ?ã ???c tôi mã hóa sang Base64 cho ?? ?? dài b?o m?t 256-bit
jwt.secret=Y3liZXJzaGllbGRfYWNhZGVteV9zdXBlcl9zZWNyZXRfa2V5XzIwMjZfMjU2Yml0cw==
jwt.expiration=3600000

# 5. C?u hình ?? hi?n th? ??y ?? l?i khi dev
server.error.include-message=always

# 6. Swagger UI ?? test API
springdoc.swagger-ui.path=/swagger-ui.html